require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Enabled: false

Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - has_previous?
    - has_next?

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
